### DISCUSSION TITLE
partitioned elements number (10000) has exeeded the threshold (4096) - using HLS4ML_tutorial

### DISCUSSION THREAD

**Discussion by Stefanvanaardt** [fastmachinelearning/hls4ml#858] [General]
Good day, all,
I am new to hls4ml, so please excuse my lack of knowledge. I have read almost any discussion and forum I can find on this problem and this is my last resort.
I have successfully tested very small autoencoder networks (synthesis and building in Vivado), however, I run into problems when implementing anything of a larger size. To see if the problem was on my side, I downloaded and ran the docker (with Vivado) as per the tutorial and cloned the stipulated repository by git clone https://github.com/fastmachinelearning/hls4ml-tutorial. The version of hls4ml used is 0.7.1.

I used the following test model KERAS_dense_16x100x100x100x100x100x5.json, and ran the following in Jupyter Notebook:

```
import hls4ml
config = hls4ml.utils.fetch_example_model('KERAS_dense_16x100x100x100x100x100x5.json')
print(config)
Downloading example model files ...
{'OutputDir': 'my-hls-test', 'ProjectName': 'myproject', 'Backend': 'Vivado', 'Part': 'xcku115-flvb2104-2-i', 'ClockPeriod': 5, 'IOType': 'io_parallel', 'HLSConfig': {'Model': {'Precision': 'ap_fixed<16,6>', 'ReuseFactor': 1}}, 'KerasJson': 'KERAS_dense_16x100x100x100x100x100x5.json', 'KerasH5': 'KERAS_dense_16x100x100x100x100x100x5_weights.h5'}
Interpreting Model
Topology:
Layer name: input_1, layer type: InputLayer, input shapes: [[None, 16]], output shape: [None, 16]
Layer name: fc1_relu, layer type: Dense, input shapes: [[None, 16]], output shape: [None, 100]
Layer name: fc2_relu, layer type: Dense, input shapes: [[None, 100]], output shape: [None, 100]
Layer name: fc3_relu, layer type: Dense, input shapes: [[None, 100]], output shape: [None, 100]
Layer name: fc4_relu, layer type: Dense, input shapes: [[None, 100]], output shape: [None, 100]
Layer name: fc5_relu, layer type: Dense, input shapes: [[None, 100]], output shape: [None, 100]
Layer name: output_softmax, layer type: Dense, input shapes: [[None, 100]], output shape: [None, 5]
Creating HLS model
hls_model = hls4ml.converters.keras_to_hls(config)
hls_model.compile()
Writing HLS project
Done    
```

I then modified the hls4ml_config.yml (and part number in project.tcl) file as per the below by modifying the strategy, the IOtype to both stream and parallel, and the reuse factor to 2000, additionally i changed the FPGA part number to one installed):

```
Backend: Vivado
ClockPeriod: 5
HLSConfig:
  Model:
    Precision: ap_fixed<16,6>
    ReuseFactor: 2000
    Strategy: Resource
IOType: io_stream
KerasH5: KERAS_dense_16x100x100x100x100x100x5_weights.h5
KerasJson: KERAS_dense_16x100x100x100x100x100x5.json
OutputDir: my-hls-test
Part: xcu250-figd2104-2L-e
ProjectName: myproject
Stamp: 85e47f44

```

as well as:

```
Backend: Vivado
ClockPeriod: 5
HLSConfig:
  Model:
    Precision: ap_fixed<16,6>
    ReuseFactor: 2000
    Strategy: Resource
IOType: io_parallel
KerasH5: KERAS_dense_16x100x100x100x100x100x5_weights.h5
KerasJson: KERAS_dense_16x100x100x100x100x100x5.json
OutputDir: my-hls-test
Part: xcu250-figd2104-2L-e
ProjectName: myproject
Stamp: 85e47f44

```

following this, building the project results in the following errors in all cases:
hls_model.build()

```
ERROR: [XFORM 203-103] Array 'mult.V' (firmware/nnet_utils/nnet_dense_latency.h:17): partitioned elements number (10000) has exeeded the threshold (4096), which may cause long run-time.
ERROR: [HLS 200-70] Pre-synthesis failed.
command 'ap_source' returned error code
    while executing
"source build_prj.tcl"
    ("uplevel" body line 1)
    invoked from within
"uplevel \#0 [list source $arg] "

INFO: [Common 17-206] Exiting vivado_hls at Mon Aug 28 02:45:59 2023...
CSynthesis report not found.
Vivado synthesis report not found.
Cosim report not found.
Timing report not found.
Found 1 solution(s) in my-hls-test/myproject_prj.
Reports for solution "solution1":
```
The same also happens when I use the tutorial examples and manually increase the network size. 
Thank you for any assistance in advance.
Stefan
