### ISSUE TITLE
Small Conv2D model synthesis running for days

### ISSUE THREAD

**Issue by bengook** [fastmachinelearning/hls4ml#242]
Hello,

I am attempting to synthesize my own small Conv2D keras model,
```
Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
=================================================================
conv2d (Conv2D)              (None, 508, 1, 16)        304       
_________________________________________________________________
activation (Activation)      (None, 508, 1, 16)        0         
_________________________________________________________________
dropout (Dropout)            (None, 508, 1, 16)        0         
_________________________________________________________________
conv2d_1 (Conv2D)            (None, 250, 1, 16)        2320      
_________________________________________________________________
activation_1 (Activation)    (None, 250, 1, 16)        0         
_________________________________________________________________
dropout_1 (Dropout)          (None, 250, 1, 16)        0         
_________________________________________________________________
conv2d_2 (Conv2D)            (None, 121, 1, 8)         1160      
=================================================================
Total params: 3,784
Trainable params: 3,784
Non-trainable params: 0
_________________________________________________________________
```
using hls4ml v0.4.0 and Vivado HLS 2017.2  (although I'm also trying 2018.2 and 2019.1 with the maximum partitions increased) on Ubuntu 18.04.5, and the vivado_hls C/RTL Synthesis has been stuck at the hardware synthesis for several days now. I've attached the [vivado_hls.log](https://github.com/fastmachinelearning/hls4ml/files/5525876/vivado_hls.log) file, and the keras-config.yml is:
```
KerasJson: sm_fullyconv2d_minimodrec.json
KerasH5:   sm_fullyconv2d_minimodrec.h5
#InputData: keras/KERAS_3layer_input_features.dat
#OutputPredictions: keras/KERAS_3layer_predictions.dat
OutputDir: hls-fullyCNN-minimod
ProjectName: myproject
XilinxPart: xc7k410tffg900-2 
#xcku115-flvb2104-2-i
ClockPeriod: 5

IOType: io_parallel # options: io_serial/io_parallel
HLSConfig:
  Model:
    Precision: ap_fixed<13,6>
    ReuseFactor: 64
    Strategy: Resource
```

I have successfully synthesized the example model, Keras_conv2d_model, using hls4ml v0.4.0 and Vivado HLS 2017.2 in a matter of minutes, which has on the order of the same number or parameters as my model, but I am out of ideas as to why my model gets stuck. Any help would be greatly appreciated. 

Thanks.
