### ISSUE TITLE
Create and deploy block design 

### ISSUE THREAD

**Issue by HenningCode** [fastmachinelearning/hls4ml#491]
Hey Guys,

I worked with hls4ml the past few months and now I finally wanted to deploy a model I transformed with hls4ml, but I dont really know how I have to initialize my IP core created with hls4ml. 
I attached my Block design I tried to get work, but again I struggle to init the ip core. 
![Block_Design](https://user-images.githubusercontent.com/57907680/150001801-f3b7a4d1-40ab-4109-87e4-2ee5b6998ab3.png)

To explore a little bit further I looked into an example of @jmduarte tiny-0.5 example. The Ip cores look completely I know that the version of hls4ml used for this example is a lot older but I feel like it should look at least a little bit the same.  I found two differences in the config, I used `io_stream` and @jmduarte used `io_parallel` and I am trying to target a zcu104 and not a pynq-z2.

![Block_Design_Tutorialk](https://user-images.githubusercontent.com/57907680/150001802-689908be-bb9f-418c-9cca-e9e492ea57c3.png)

Any tips on how I should try to go forward would be appreciated. 

I could also attach the code I got so far in the sdk, but I dont think that would help, but this is my hls4ml config.

``` 
    backend_config = {}
    backend_config['HLSConfig'] = config
    backend_config['Backend'] = 'Vivado'
    backend_config['ClockPeriod'] = 1
    backend_config['IOType'] = 'io_stream'
    backend_config['OutputDir'] = output_dir+'/cnn2_hls'
    backend_config['ProjectName'] = 'mnist_test'
    backend_config['XilinxPart']= 'xczu7ev-ffvc1156-2-e'
    backend_config['Interface'] = 'm_axi'

```
And this is my config:

```
LayerName:
  input_1_m:
    Precision:
      result: ap_fixed<16,6>
  qact_1_m:
    Precision:
      result: ap_ufixed<4,2>
    ReuseFactor: 300000
  qact_2_m:
    Precision:
      result: ap_ufixed<4,2>
    ReuseFactor: 300000
  qdense_1_m:
    Precision:
      bias: ap_fixed<5,1>
      weight: ap_fixed<5,1>
    ReuseFactor: 300000
  qdense_2_m:
    Precision:
      bias: ap_fixed<5,1>
      weight: ap_fixed<5,1>
    ReuseFactor: 300000
  qdense_3_m:
    Precision:
      bias: ap_fixed<5,1>
      weight: ap_fixed<5,1>
    ReuseFactor: 300000
  sact_1_m:
    Precision: ap_fixed<16,6>
    ReuseFactor: 300000
    exp_table_t: ap_fixed<18,8,AP_RND,AP_SAT>
    inv_table_t: ap_fixed<18,8,AP_RND,AP_SAT>
    table_size: 1024
Model:
  Precision: ap_fixed<16,6>
  ReuseFactor: 300000
  Strategy: Resource

```
